name = "GridGeometryUtils"
uuid = "6f784e4f-3d6e-439e-b87e-1b67132dd330"
authors = ["Albert de Montserrat <albert.de.montserrat@gmail.com>"]
version = "0.1.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[compat]
Adapt = "4.3.0"
Test = "1.10, 1.11"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
